<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
    <PackageReference
            Include="Microsoft.EntityFrameworkCore.Design"
            Version="9.0.0"
        >
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets
            >runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference
            Include="..\CalendarLife.Domain\CalendarLife.Domain.csproj"
        />
    <ProjectReference
            Include="..\CalendarLife.Application\CalendarLife.Application.csproj"
        />
    <ProjectReference
            Include="..\CalendarLife.Infrastructure\CalendarLife.Infrastructure.csproj"
        />
  </ItemGroup>

</Project>
