// <auto-generated />
using System;
using CalendarLife.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CalendarLife.Infrastructure.Migrations
{
    [DbContext(typeof(CalendarLifeDbContext))]
    [Migration("20260507222950_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CalendarLife.Domain.Entities.DailyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayIndex")
                        .HasColumnType("integer");

                    b.Property<int>("DayStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Journal")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DayIndex")
                        .IsUnique();

                    b.ToTable("DailyRecords");
                });

            modelBuilder.Entity("CalendarLife.Domain.Entities.DailyTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyRecordId")
                        .HasColumnType("uuid");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SourceDefaultTaskId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DailyRecordId");

                    b.HasIndex("SourceDefaultTaskId");

                    b.ToTable("DailyTasks");
                });

            modelBuilder.Entity("CalendarLife.Domain.Entities.DefaultTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DefaultTasks");
                });

            modelBuilder.Entity("CalendarLife.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CalendarLife.Domain.Entities.UserSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("SetupCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowHelp")
                        .HasColumnType("boolean");

                    b.Property<int>("SquareSize")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("CalendarLife.Domain.Entities.DailyRecord", b =>
                {
                    b.HasOne("CalendarLife.Domain.Entities.User", "User")
                        .WithMany("DailyRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalendarLife.Domain.Entities.DailyTask", b =>
                {
                    b.HasOne("CalendarLife.Domain.Entities.DailyRecord", "DailyRecord")
                        .WithMany("DailyTasks")
                        .HasForeignKey("DailyRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalendarLife.Domain.Entities.DefaultTask", "SourceDefaultTask")
                        .WithMany()
                        .HasForeignKey("SourceDefaultTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DailyRecord");

                    b.Navigation("SourceDefaultTask");
                });

            modelBuilder.Entity("CalendarLife.Domain.Entities.DefaultTask", b =>
                {
                    b.HasOne("CalendarLife.Domain.Entities.User", "User")
                        .WithMany("DefaultTasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalendarLife.Domain.Entities.UserSetting", b =>
                {
                    b.HasOne("CalendarLife.Domain.Entities.User", "User")
                        .WithOne("Setting")
                        .HasForeignKey("CalendarLife.Domain.Entities.UserSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalendarLife.Domain.Entities.DailyRecord", b =>
                {
                    b.Navigation("DailyTasks");
                });

            modelBuilder.Entity("CalendarLife.Domain.Entities.User", b =>
                {
                    b.Navigation("DailyRecords");

                    b.Navigation("DefaultTasks");

                    b.Navigation("Setting");
                });
#pragma warning restore 612, 618
        }
    }
}
